# Generated by Django 3.0 on 2019-12-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocialAuth',
        ),
    ]
